# Generated by Django 4.0.2 on 2022-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_samples',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='work_samples',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='work_samples',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='work_samples',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
